"""create perfil_usuario

Revision ID: e2cd74e5cd2f
Revises: afe9b9a4d7ed
Create Date: 2026-04-09 10:08:19.182007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2cd74e5cd2f'
down_revision: Union[str, Sequence[str], None] = 'afe9b9a4d7ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('centro_costo_id', sa.Integer(), nullable=True),
    sa.Column('nombres', sa.String(), nullable=False),
    sa.Column('apellidos', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['centro_costo_id'], ['centro_costos.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_perfil_usuarios_id'), 'perfil_usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_perfil_usuarios_id'), table_name='perfil_usuarios')
    op.drop_table('perfil_usuarios')
    # ### end Alembic commands ###
