"""remove correo from perfil_usuario

Revision ID: ee2d06792c41
Revises: f76724d19d17
Create Date: 2026-04-10 10:38:38.030473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee2d06792c41'
down_revision: Union[str, Sequence[str], None] = 'f76724d19d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('perfil_usuarios_correo_key'), 'perfil_usuarios', type_='unique')
    op.drop_column('perfil_usuarios', 'correo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfil_usuarios', sa.Column('correo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('perfil_usuarios_correo_key'), 'perfil_usuarios', ['correo'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
