"""create centro_costo table

Revision ID: ee9e8786c2de
Revises: 21d0f144ca09
Create Date: 2026-04-08 12:56:48.215587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9e8786c2de'
down_revision: Union[str, Sequence[str], None] = '21d0f144ca09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centro_costos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centro_costos_id'), 'centro_costos', ['id'], unique=False)
    op.create_index(op.f('ix_centro_costos_nombre'), 'centro_costos', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_centro_costos_nombre'), table_name='centro_costos')
    op.drop_index(op.f('ix_centro_costos_id'), table_name='centro_costos')
    op.drop_table('centro_costos')
    # ### end Alembic commands ###
